export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const REQUEST_ARTICLES_SUCCESS = 'REQUEST_ARTICLES_SUCCESS';
export const REQUEST_ARTICLES_FAIL = 'REQUEST_ARTICLES_FAIL';
export const CHANGE_PAGE = 'CHANGE_PAGE';
